services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
    # backend:
    #     image: go-ksiazki-server
    #     build:
    #         context: backend
    #         dockerfile: ../Dockerfile
    #     ports:
    #         - 8080:8080

volumes:
    pgdata:
